os:
  - linux
services:
  - docker
install:
  - docker build -t jhipster/jhipster-registry:travis .
  - docker images
  - docker run --name jhipster-registry -p 8761:8761 -d -t jhipster/jhipster-registry:travis
before_script:
# 登录到 docker hub
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - sleep 45
  - docker ps
  - docker logs jhipster-registry
  - curl -v http://localhost:8761

after_success:
# 当代码测试通过后执行的命令
- docker build -t tarra201406/jhipster-registry .
- docker push tarra201406/jhipster-registry

